# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Bicep-Resource-Deployment

trigger:
- bicep

variables:
  resourceGroupName: 'rg-rituraj-tiwari'
  location: 'eastus'
  azureSubscription: 'azbiceps'
#  environment_name: 'dev'

pool:
  name: default
  vmImage:  'ubuntu-20.04'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(azureSubscription) 
        scriptType: 'ps'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file main.bicep'
    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container'
- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create `
                --template-file $(Build.SourcesDirectory)/main.bicep `
                --parameters $(Build.SourcesDirectory)/dev.param.json `
                --resource-group $(ResourceGroupName)
#                --parameters environment_name=$(environment_name)